import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import { lazySchema } from '../../utils/lazySchema.js'
import { jsonStringify } from '../../utils/slowOperations.js'

const inputSchema = lazySchema(() =>
  z.strictObject({
    artifact_id: z
      .string()
      .min(1)
      .describe('Artifact identifier to review/analyze'),
    instructions: z
      .string()
      .optional()
      .describe('Optional review focus/instructions'),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>
type Input = z.infer<InputSchema>

const outputSchema = lazySchema(() =>
  z.object({
    artifact_id: z.string(),
    status: z.enum(['accepted']),
    message: z.string(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const ReviewArtifactTool = buildTool({
  name: 'ReviewArtifact',
  searchHint: 'review an internal artifact by id',
  maxResultSizeChars: 100_000,
  shouldDefer: true,
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  isConcurrencySafe() {
    return true
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input: Input) {
    return `review_artifact:${input.artifact_id}`
  },
  async description() {
    return 'Review an artifact generated by the system.'
  },
  async prompt() {
    return 'Review artifact metadata and return a concise status summary.'
  },
  async call(input: Input) {
    return {
      data: {
        artifact_id: input.artifact_id,
        status: 'accepted',
        message: `Artifact ${input.artifact_id} accepted for review.`,
      },
    }
  },
  mapToolResultToToolResultBlockParam(output: Output, toolUseID: string) {
    return {
      tool_use_id: toolUseID,
      type: 'tool_result',
      content: jsonStringify(output),
    }
  },
  renderToolUseMessage(input: Partial<Input>) {
    return `ReviewArtifact(${input.artifact_id ?? 'unknown'})`
  },
  renderToolResultMessage(output: Output) {
    return output.message
  },
} satisfies ToolDef<InputSchema, Output>)
